version = 1

[merge]
require_automerge_label = false
blocking_labels = ["do not merge"]
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
strip_html_comments = true
include_coauthors = true
